os:
  - linux

language: python

services:
  - docker

before_install:
  - docker pull continuumio/miniconda3
  - docker run --mount type=bind,source=$PWD,destination=/workflow continuumio/miniconda3 /bin/bash -c "cd /workflow; test/test1.sh test-results"


