name: DKFZ-ODCF_Bam2Fastq
channels:
  - conda-forge
  - bioconda
  - bioconda-legacy
  - defaults
channel_priority: flexible
dependencies:
  - bash=4.4.18
  - biobambam=2.0.87
  - mbuffer=20160228
  - openjdk=8.0.144
  - pbzip2=1.1.13
  - perl=5.22.2.1
  - picard=2.14.1
  - pigz=2.3.4
  - python=3.6
  - samtools=1.5
  - filelock=3.0.12

