name: nf-bam2fastq 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash=5.0.018
  - biobambam=2.0.179
  - mbuffer=20160228
  - perl=5.22.2.1
  - pigz=2.3.4
  - python=3.6
  - samtools=1.11
