# If there is a tag following the pattern \d+\.\d+\.\d+ is made on the master
# branch, then release two containers "dkfz-odcf/nf-bam2fastq" with the
# version tags $tag and "latest"
name: Docker Image CI

on:
  # Only release the container for new tags pushed to master branch.
  push:
    branches:
      - master
    tags:
      # Only publish containers for semantic versioning tags.
      - '[1-9]+.[0-9]+.[0-9]+'

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build ./ --file Dockerfile --tag nf-bam2fastq:latest
      - name: Login to ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: '${{ secrets.GHCR_TOKEN }}'
          logout: true # optional, default is true
      - name: Push image
        uses: docker/build-push-action@v2
        env:
          tag: '${GITHUB_REF#refs/*/}'
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:$tag
            ghcr.io/${{ github.repository }}:latest
