# If there is a tag following the pattern \d+\.\d+\.\d+ is made on the master
# branch, then release two containers "dkfz-odcf/nf-bam2fastq" with the
# version tags $tag and "latest"
name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '\d+\.\d+\.\d+'

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/DKFZ-ODCF/nf-bam2fastq
          tags: |
            type=ref,event=tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
